const Router = require('express')
const usersRouter = require('./users.router')
const servicesRouter = require('./services.router')
const companiesRouter = require('./companies.router')
const vehicleBrandsRouter = require('./vehicleBrands.router')
const vehicleModelsRouter = require('./vehicleModels.router')
const parkingsRouter = require('./parkings.router')
const deliveryTypesRouter = require('./deliveryTypes.router')
const vehicleMovesRouter = require('./vehicleMoves.router')
const vehicleTypesRouter = require('./vehicleTypes.router')
const driversRouter = require('./drivers.router')
const driverHistoryRouter = require('./driverHistory.router')
const authRouter = require('./auth.router')
const publicRouter = require('./publicData.router')
const checkAuth = require('../middleware/checkAuth')

const router = Router()
router.use('/users', checkAuth, usersRouter)
router.use('/services', checkAuth, servicesRouter)
router.use('/companies', checkAuth, companiesRouter)
router.use('/vehicle/brands', checkAuth, vehicleBrandsRouter)
router.use('/vehicle/models', checkAuth, vehicleModelsRouter)
router.use('/parkings', checkAuth, parkingsRouter)
router.use('/deliveryTypes', checkAuth, deliveryTypesRouter)
router.use('/vehicleMoves', checkAuth, vehicleMovesRouter)
router.use('/vehicleTypes', checkAuth, vehicleTypesRouter)
router.use('/drivers', checkAuth, driversRouter)
router.use('/driverHistory', checkAuth, driverHistoryRouter)
router.use('/auth', authRouter)
router.use('/publicData', publicRouter)


module.exports = router